# Generated by Django 3.2.5 on 2021-12-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99)),
                ('slug', models.SlugField()),
                ('description', models.TextField(max_length=800)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
