# Generated by Django 3.2.5 on 2021-10-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfp', models.ImageField(default='static/gamers/images/defpfp.jpg', upload_to='')),
                ('description', models.TextField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
    ]
