# Generated by Django 3.2.8 on 2021-10-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamer',
            name='url',
        ),
        migrations.AlterField(
            model_name='gamer',
            name='pfp',
            field=models.ImageField(upload_to='./uploaded'),
        ),
    ]
