# Generated by Django 3.2.8 on 2021-10-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0008_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='I love GamersDen!', max_length=100),
        ),
    ]
