# Generated by Django 3.2.8 on 2021-10-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0012_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='I love Gamers Den!'),
        ),
    ]
