# Generated by Django 3.2.8 on 2021-10-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0013_auto_20211027_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
