# Generated by Django 3.2.5 on 2021-12-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Steam',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile_pics'),
        ),
    ]
