# Generated by Django 3.2.5 on 2021-12-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUsers', '0002_auto_20211204_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
