# Generated by Django 3.2.10 on 2021-12-31 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUsers', '0004_followercount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowerCount',
        ),
    ]
