# Generated by Django 3.2.10 on 2022-01-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUsers', '0005_delete_followercount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='I am a GAMER!', null=True),
        ),
    ]
