# Generated by Django 3.2.5 on 2021-12-12 09:19

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserPosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=ckeditor.fields.RichTextField(default='My game is awesome :D', max_length=500),
        ),
        migrations.AddField(
            model_name='game',
            name='published_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='steam_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
