# Generated by Django 3.2.8 on 2021-11-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposts',
            name='thumb',
            field=models.ImageField(default='static/user_posts/images/noimg.png', upload_to=''),
        ),
    ]
