# Generated by Django 3.2.5 on 2021-12-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPosts', '0002_auto_20211208_0947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
