# Generated by Django 3.2.5 on 2021-12-12 09:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPosts', '0002_auto_20211212_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
