# Generated by Django 3.2.8 on 2021-11-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPosts', '0002_userposts_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='thumb',
            field=models.ImageField(default='UserPosts/static/user_posts/images/noimg.png', upload_to=''),
        ),
    ]
