# Generated by Django 3.2.8 on 2021-11-09 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserPosts', '0004_videoupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposts',
            name='posted_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
