# Generated by Django 3.2.5 on 2021-12-12 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserPosts', '0005_alter_game_published_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(default='Minecraft', max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='game_image',
            field=models.ImageField(default='UserPosts/static/user_posts/images/game.png', upload_to='game/images'),
        ),
        migrations.AddField(
            model_name='game',
            name='likes',
            field=models.ManyToManyField(related_name='liked_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
