# Generated by Django 3.2.8 on 2021-11-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPosts', '0005_userposts_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
