# Generated by Django 3.2.8 on 2021-11-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPosts', '0006_alter_userposts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
