# Generated by Django 3.2.5 on 2021-12-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPosts', '0006_auto_20211212_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('Shooter', 'Shotter'), ('RPG', 'RPG'), ('Online', 'Online'), ('Offline', 'Offline')], default='Shooter', max_length=255),
        ),
    ]
