# Generated by Django 3.2.5 on 2021-12-12 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserPosts', '0007_alter_game_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('Shooter', 'Shooter'), ('RPG', 'RPG'), ('Online', 'Online'), ('Offline', 'Offline')], default='Shooter', max_length=255),
        ),
        migrations.AlterField(
            model_name='game',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='liked_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
