# Generated by Django 3.2.5 on 2021-12-12 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserPosts', '0009_auto_20211212_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='published_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
