# Generated by Django 3.2.8 on 2021-11-10 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserPosts', '0009_alter_userposts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userposts',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
