# Generated by Django 3.2.5 on 2021-11-24 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserPosts', '0011_addgame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AddGame',
        ),
        migrations.RemoveField(
            model_name='userposts',
            name='posted_by',
        ),
        migrations.DeleteModel(
            name='VideoUpload',
        ),
        migrations.DeleteModel(
            name='UserPosts',
        ),
    ]
