# Generated by Django 3.2.10 on 2021-12-31 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserPosts', '0012_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='likes',
            field=models.ManyToManyField(related_name='game_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='explore_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
