# Generated by Django 3.2.10 on 2021-12-31 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPosts', '0013_auto_20211231_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='likes',
            new_name='game_likes',
        ),
    ]
