# Generated by Django 3.2.5 on 2021-11-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPosts', '0014_auto_20211127_1324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Game',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='game',
        ),
    ]
