# Generated by Django 3.2.10 on 2021-12-31 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPosts', '0014_rename_likes_game_game_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_likes',
            new_name='likes',
        ),
    ]
