# Generated by Django 3.2.5 on 2021-12-01 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserPosts', '0015_auto_20211127_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='game_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
