# Generated by Django 3.2.10 on 2022-01-01 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserPosts', '0015_rename_game_likes_game_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserPosts.post')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
