# Generated by Django 3.2.10 on 2022-01-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPosts', '0017_auto_20220101_0930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamecomment',
            options={},
        ),
        migrations.RenameField(
            model_name='gamecomment',
            old_name='created',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='gamecomment',
            old_name='post',
            new_name='game',
        ),
        migrations.RemoveField(
            model_name='gamecomment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='gamecomment',
            name='name',
        ),
        migrations.AddField(
            model_name='gamecomment',
            name='body',
            field=models.TextField(default=None, max_length=255),
        ),
    ]
