# Generated by Django 3.2.10 on 2022-01-01 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserPosts', '0018_auto_20220101_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecomment',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamecomments', to='UserPosts.game'),
        ),
        migrations.AlterField(
            model_name='gamecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamecomments', to=settings.AUTH_USER_MODEL),
        ),
    ]
