# Generated by Django 3.2.5 on 2021-12-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPosts', '0021_alter_post_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(default='UserPosts/static/user_posts/images/game.png', upload_to='user/images'),
        ),
    ]
