# Generated by Django 3.2.5 on 2021-12-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPosts', '0024_auto_20211207_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated',
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
