# Generated by Django 3.2.10 on 2021-12-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bottom_header',
        ),
        migrations.DeleteModel(
            name='center_header',
        ),
        migrations.DeleteModel(
            name='top_header',
        ),
    ]
